name: unit_7_assignment_maquiran
description: "A new Flutter project."
publish_to: 'none' # This ensures the package is private and not published.
version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0" # Defines the Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_expanded_tile: 0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
